name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Install Dependencies (Github Pages)
      run: npm install
      working-directory: ./docs

    - name: Run Tests (Github Pages)
      run: npm test
      working-directory: ./docs
